debug: true
color_threshold: 10
process_size: 32
window_stride: 16
roi_upper: 0.8
#roi_upper: 0.5
roi_lower: 1.0
scale_x: 0.4
scale_y: 0.4
target_hue: 35
minimum_pixel: 5
target_value: 35
subscribe_from_rostopic: false
topic_name: '/pylon_camera_node/image_raw'
webcam_on: false
webcam_port: 1
video_filename: 'lol.avi'
#video_filename: 'test.webm'
hog_filename: 'param/hog32.yml'
svm_filename: 'param/svm32.yml'
