debug: true
color_threshold: 10
process_size: 32
window_stride: 4
roi_upper: 0.5
#roi_upper: 0.5
roi_lower: 1.0
scale_x: 0.5
scale_y: 0.5
target_hue: 65
minimum_pixel: 20
target_value: 0
subscribe_from_topic: true
topic_name: '/camera'
webcam_on: false
webcam_port: 1
video_filename: 'lol.avi'
#video_filename: 'test.webm'
hog_filename: 'param/hog32.yml'
svm_filename: 'param/svm32.yml'
